// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: DoorTouchControl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Main;
lv_obj_t *ui_ImageLogo;
lv_obj_t *ui_ImgButtonAuto;
lv_obj_t *ui_ImgButtonClosed;
lv_obj_t *ui_ImgButtonOpen;
lv_obj_t *ui_ImageLine1;
lv_obj_t *ui_ImageLine2;
lv_obj_t *ui_ImageLine3;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1393550909[1] = {&ui_img_1395900053};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageLogo = lv_img_create(ui_Main);
lv_img_set_src(ui_ImageLogo, &ui_img_1395900053);
lv_obj_set_width( ui_ImageLogo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageLogo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageLogo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImgButtonAuto = lv_imgbtn_create(ui_Main);
lv_imgbtn_set_src(ui_ImgButtonAuto, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_30629225, NULL);
lv_imgbtn_set_src(ui_ImgButtonAuto, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_26181796, NULL);
lv_imgbtn_set_src(ui_ImgButtonAuto, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_26181796, NULL);
lv_imgbtn_set_src(ui_ImgButtonAuto, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_26181796, NULL);
lv_obj_set_height( ui_ImgButtonAuto, 64);
lv_obj_set_width( ui_ImgButtonAuto, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonAuto, -2 );
lv_obj_set_y( ui_ImgButtonAuto, 66 );
lv_obj_set_align( ui_ImgButtonAuto, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImgButtonAuto, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImgButtonClosed = lv_imgbtn_create(ui_Main);
lv_imgbtn_set_src(ui_ImgButtonClosed, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_778841582, NULL);
lv_imgbtn_set_src(ui_ImgButtonClosed, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1916212465, NULL);
lv_imgbtn_set_src(ui_ImgButtonClosed, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1916212465, NULL);
lv_imgbtn_set_src(ui_ImgButtonClosed, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1916212465, NULL);
lv_obj_set_height( ui_ImgButtonClosed, 64);
lv_obj_set_width( ui_ImgButtonClosed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonClosed, -52 );
lv_obj_set_y( ui_ImgButtonClosed, -51 );
lv_obj_set_align( ui_ImgButtonClosed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImgButtonClosed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImgButtonOpen = lv_imgbtn_create(ui_Main);
lv_imgbtn_set_src(ui_ImgButtonOpen, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1500679202, NULL);
lv_imgbtn_set_src(ui_ImgButtonOpen, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1479539165, NULL);
lv_imgbtn_set_src(ui_ImgButtonOpen, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_1479539165, NULL);
lv_imgbtn_set_src(ui_ImgButtonOpen, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_1479539165, NULL);
lv_obj_set_height( ui_ImgButtonOpen, 64);
lv_obj_set_width( ui_ImgButtonOpen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonOpen, 49 );
lv_obj_set_y( ui_ImgButtonOpen, -49 );
lv_obj_set_align( ui_ImgButtonOpen, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImgButtonOpen, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImageLine1 = lv_img_create(ui_Main);
lv_img_set_src(ui_ImageLine1, &ui_img_653244841);
lv_obj_set_width( ui_ImageLine1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageLine1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageLine1, -72 );
lv_obj_set_y( ui_ImageLine1, 5 );
lv_obj_set_align( ui_ImageLine1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageLine1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImageLine2 = lv_img_create(ui_Main);
lv_img_set_src(ui_ImageLine2, &ui_img_897502467);
lv_obj_set_width( ui_ImageLine2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageLine2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageLine2, 0 );
lv_obj_set_y( ui_ImageLine2, -65 );
lv_obj_set_align( ui_ImageLine2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageLine2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ImageLine3 = lv_img_create(ui_Main);
lv_img_set_src(ui_ImageLine3, &ui_img_653244841);
lv_obj_set_width( ui_ImageLine3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageLine3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageLine3, 71 );
lv_obj_set_y( ui_ImageLine3, 5 );
lv_obj_set_align( ui_ImageLine3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageLine3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
