// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: DoorTouchControl

#ifndef _DOORTOUCHCONTROL_UI_H
#define _DOORTOUCHCONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_ImageLogo;
extern lv_obj_t *ui_ImgButtonAuto;
extern lv_obj_t *ui_ImgButtonClosed;
extern lv_obj_t *ui_ImgButtonOpen;
extern lv_obj_t *ui_ImageLine1;
extern lv_obj_t *ui_ImageLine2;
extern lv_obj_t *ui_ImageLine3;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_1395900053);   // assets\AB-SmartHouseLogo-48x48.png
LV_IMG_DECLARE( ui_img_30629225);   // assets\auto-released.png
LV_IMG_DECLARE( ui_img_26181796);   // assets\auto-pressed.png
LV_IMG_DECLARE( ui_img_778841582);   // assets\closed-released.png
LV_IMG_DECLARE( ui_img_1916212465);   // assets\closed-pressed.png
LV_IMG_DECLARE( ui_img_1500679202);   // assets\open-released.png
LV_IMG_DECLARE( ui_img_1479539165);   // assets\open-pressed.png
LV_IMG_DECLARE( ui_img_653244841);   // assets\line-horizontal.png
LV_IMG_DECLARE( ui_img_897502467);   // assets\line-vertical.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
